version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: restaurant_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: "mysql"
            DB_HOST: "mysql"
            DB_PORT: "3306"
            DB_DATABASE: "laravel"
            DB_USERNAME: "sail"
            DB_PASSWORD: "password"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
        depends_on:
            - mysql
            - redis
        restart: always

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "laravel"
            MYSQL_USER: "sail"
            MYSQL_PASSWORD: "password"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always

    redis:
        image: redis:7
        container_name: redis_cache
        ports:
            - "6379:6379"
        restart: always

volumes:
    mysql_data:
